name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: readme.md
          feed_list: "https://dev.to/feed/fferegrino, https://medium.com/feed/@antonio.feregrino, https://www.youtube.com/feeds/videos.xml?channel_id=UC8KCb358oioQMcJ5pUfs8UQ"
